# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/camille/ENPC-TDLOG-project-Flashcards/createcards.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(497, 492)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayoutWidget = QtWidgets.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 451, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.answergrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.answergrid.setContentsMargins(0, 0, 0, 0)
        self.answergrid.setObjectName("answergrid")
        self.myproficiency = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myproficiency.setObjectName("myproficiency")
        self.answergrid.addWidget(self.myproficiency, 7, 0, 1, 1)
        self.myexample = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myexample.setObjectName("myexample")
        self.answergrid.addWidget(self.myexample, 5, 0, 1, 1)
        self.editdiffult = QtWidgets.QSlider(self.gridLayoutWidget)
        self.editdiffult.setOrientation(QtCore.Qt.Horizontal)
        self.editdiffult.setObjectName("editdiffult")
        self.answergrid.addWidget(self.editdiffult, 6, 1, 1, 1)
        self.edittrad = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edittrad.setObjectName("edittrad")
        self.answergrid.addWidget(self.edittrad, 2, 1, 1, 1)
        self.mytrad = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mytrad.setObjectName("mytrad")
        self.answergrid.addWidget(self.mytrad, 2, 0, 1, 1)
        self.myword = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myword.setObjectName("myword")
        self.answergrid.addWidget(self.myword, 1, 0, 1, 1)
        self.difficult = QtWidgets.QLabel(self.gridLayoutWidget)
        self.difficult.setObjectName("difficult")
        self.answergrid.addWidget(self.difficult, 6, 0, 1, 1)
        self.editthema = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editthema.setObjectName("editthema")
        self.answergrid.addWidget(self.editthema, 3, 1, 1, 1)
        self.editword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editword.setObjectName("editword")
        self.answergrid.addWidget(self.editword, 1, 1, 1, 1)
        self.editexample = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.editexample.setObjectName("editexample")
        self.answergrid.addWidget(self.editexample, 5, 1, 1, 1)
        self.mythema = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mythema.setObjectName("mythema")
        self.answergrid.addWidget(self.mythema, 3, 0, 1, 1)
        self.editprofiency = QtWidgets.QSlider(self.gridLayoutWidget)
        self.editprofiency.setOrientation(QtCore.Qt.Horizontal)
        self.editprofiency.setObjectName("editprofiency")
        self.answergrid.addWidget(self.editprofiency, 7, 1, 1, 1)
        self.mynature = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mynature.setObjectName("mynature")
        self.answergrid.addWidget(self.mynature, 8, 0, 1, 1)
        self.editnature = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.editnature.setObjectName("editnature")
        self.answergrid.addWidget(self.editnature, 8, 1, 1, 1)
        self.mysound = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mysound.setObjectName("mysound")
        self.answergrid.addWidget(self.mysound, 11, 0, 1, 1)
        self.myillustration = QtWidgets.QLabel(self.gridLayoutWidget)
        self.myillustration.setObjectName("myillustration")
        self.answergrid.addWidget(self.myillustration, 10, 0, 1, 1)
        self.mylanguage = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mylanguage.setObjectName("mylanguage")
        self.answergrid.addWidget(self.mylanguage, 9, 0, 1, 1)
        self.chooseButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.chooseButton2.setObjectName("chooseButton2")
        self.answergrid.addWidget(self.chooseButton2, 11, 1, 1, 1)
        self.chooseButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.chooseButton1.setObjectName("chooseButton1")
        self.answergrid.addWidget(self.chooseButton1, 10, 1, 1, 1)
        self.editlanguage = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.editlanguage.setObjectName("editlanguage")
        self.answergrid.addWidget(self.editlanguage, 9, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.togivename = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.togivename.setContentsMargins(0, 0, 0, 0)
        self.togivename.setObjectName("togivename")
        self.mycardname = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.mycardname.setObjectName("mycardname")
        self.togivename.addWidget(self.mycardname)
        self.setname = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.setname.setObjectName("setname")
        self.togivename.addWidget(self.setname)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 400, 451, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.tocreate = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.tocreate.setContentsMargins(0, 0, 0, 0)
        self.tocreate.setObjectName("tocreate")
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tocreate.addWidget(self.progressBar)
        self.createButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.createButton.setObjectName("createButton")
        self.tocreate.addWidget(self.createButton)
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.createButton.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.myproficiency.setText(_translate("Frame", " Entrez votre niveau de maitrise :"))
        self.myexample.setText(_translate("Frame", " Entrez une phrase d\'exemple : "))
        self.mytrad.setText(_translate("Frame", " Entrez sa traduction : "))
        self.myword.setText(_translate("Frame", " Entrez votre mot :"))
        self.difficult.setText(_translate("Frame", " Entrez la difficulté : "))
        self.mythema.setText(_translate("Frame", " Entrez le thème : "))
        self.mynature.setText(_translate("Frame", " Selectionez la nature du mot :"))
        self.mysound.setText(_translate("Frame", " Selectionez une prononciation :"))
        self.myillustration.setText(_translate("Frame", " Selectionez une image :"))
        self.mylanguage.setText(_translate("Frame", " Selectionez la langue :"))
        self.chooseButton2.setText(_translate("Frame", "Choisir"))
        self.chooseButton1.setText(_translate("Frame", "Choisir"))
        self.mycardname.setText(_translate("Frame", " Entrez le nom de votre carte :"))
        self.createButton.setText(_translate("Frame", "Create"))

